defaults:
  - _self_
  - override hydra/launcher:  local
  - override hydra/output:  local

# snapshot
save_snapshot: false
load_snap: ""

# replay buffer
num_workers: 0
batch_size: 32 
train_steps: 8001
eval_freq: 1000

# misc
seed: 1
device: cuda

# experiment
experiment: train_iql
wandbuser: 
wandbproject: 

# data
dataset: kitchen-complete-v0

agent:
  _target_: vip.models.model_iql.StateIQL
  device: ${device}
  lr: 1e-4
  state_dim: 60
  action_dim: 9
  hidden_dim: 256
  size: 1
  mlp_width: 256
  expectile: 0.7
  beta: 3.0
  max_adv: 100.0
