defaults:
  - _self_
  - override hydra/launcher:  local
  - override hydra/output:  local

# snapshot
save_snapshot: false
load_snap: ""

# replay buffer
num_workers: 0
batch_size: 32 
train_steps: 8001
eval_freq: 1000

# misc
seed: 1
device: cuda

# experiment
experiment: train_vip
wandbuser: 
wandbproject: 

# data
dataset: kitchen-complete-v0
datapath: 
doaug: "none"

agent:
  _target_: vip.models.model_vip.StateVIP
  device: ${device}
  lr: 1e-4
  state_dim: 60
  hidden_dim: 256
  size: 1
  mlp_width: 256
  l2weight: 0.0
  l1weight: 0.0
  num_negatives: 0
